ci: Fix build by locking node version
The version of graceful-fs that gitbook uses does not support higher
than node 12.16.x. GitBook will not be getting futher updates, so we
must lock the node version for builds to node 12.16.x or it fails.
If you use a higher node version, you'll get this error:
  `TypeError: cb.apply is not a function`